### ISSUE TITLE
Initial Swift integration feedback

### ISSUE THREAD

**Issue by pixlwave** [vector-im/compound-design-tokens#14]
Some points from my first pass at integrating `main` into ElementX iOS:
- [x] The colorsets all seem to have an alpha of 0.0039 (sorry I totally missed this on the PR).
- [x] The Swift files need to `import SwiftUI` instead of `import UIKit` to compile using `Color` values.
- [x] As this is a package the `Color` initialisers need a bundle parameter to find the asset (again, sorry I missed this on the PR): `Color("colorPink1400", bundle: Bundle.module)`

Minor:
- [ ] Something that I only recently twigged about is that you could replace all the `CGFloat(12)` values with `12.0` if it makes life easier/tidier as the Swift compiler now automatically converts a `Double` into a `CGFloat`. The multiplications are fine to remain as `mySpaceDouble * 2`, thats still valid.

**Comment by gsouquet** [comment]
Thank you for the feedback, will update all of that!

Regarding the `Double`. Is it important to have the trailing `.0` or can it be ommitted?

**Comment by pixlwave** [comment]
Thanks! Yes, `0.0` is a `Double` literal where as `0` is an `Int` literal.

**Comment by gsouquet** [comment]
Alright in that case keeping `CGFloat` is as easy as we will need to apply a transform in both cases
